typography_spectrum: 0.2712628738954663
color:
  brandStrength: 0.767991412896663
  lightness: 0.9363456359133124
  saturation: 0.4274642269592732
  rhythmicContrast: 0.3562991220969707
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
layout_spectrum: 0.11432010168209672
author:
  name: Tim Casson
  email: tim@thedancewemade.co.uk
  url: youtube.com/thedancewemade
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/44069832-9192-4c4b-b695-76578a7e27f1.jpg
name: The Dance WE Made
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51a904bc-80f1-45ad-aeb7-bd1898646e1e.jpg
title: Let's Make a Dance
